version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  app:
    image: propel_health
    restart: always
    environment:
      NODE_ENV: production

    depends_on:
      - mongo
    ports:
      - '3000:3000'



